### ISSUE TITLE
Page formatting: images in separate folders with the same filename

### ISSUE THREAD

**Issue by nickyivyca** [jonathanadams/esphome-configs#112]
I recently submitted two devices to the repo, the QIACHIP and KTNNKG RF relays. Both of them had a picture in them called 'top.jpg.' It looks like the top.jpg from the QIACHIP folder appears on both the QIACHIP and KTNNKG pages.

https://esphome-configs.io/devices/qiachip-smart-switch/
https://esphome-configs.io/devices/ktnnkg-wifi-kg2201-w/

Maybe just not having two top.jpg files in separate folders is the best option here, but this wasn't obvious when I first made the pull request.

**Comment by jonathanadams** [comment]
I think having the images in both folders is ok as it keeps everything related to a device in its own folder. Besides I believe the Netlify CDN recognises the images as the same thus not causing any performance issues when caching the images.
