### ISSUE TITLE
Question: How to handle "clone" devices

### ISSUE THREAD

**Issue by pauln** [jonathanadams/esphome-configs#56]
After getting a good deal of the way through writing an entry for an RGBWW bulb which I've been playing with recently, I went looking at existing configs to see whether any made mention of tuya-convert, as that's the simplest way to get up an running.  When I found one which mentions tuya-convert, I realised that the bulb in question seems to be a clone of the one I've been working with!

What's the preferred way to handle this situation?  A couple of options (other than adding a whole duplicate config) which spring to mind are:
- Add a config for my bulb, which just lists the name etc (and perhaps includes a photo of the bulb and/or packaging) but simply links to the existing config
- Edit the existing config to add a list of "aliases" or "clones", listing my bulb as one

**Comment by pauln** [comment]
Have you had any thoughts on this, @jonathanadams?  I've got a few devices which I'd like to submit PRs for, as they're readily available at retail in Australia and New Zealand - but some (such as the one mentioned above) match existing configs, so it'd be good to know your preferred approach to "clones" before investing too much time in writing configs which might not align.

**Comment by jonathanadams** [comment]
@pauln apologies for the delay in my reply. I prefer your first suggestion - adding a config for the bulb  listing name, picture etc and then link to the existing config.

**Comment by pauln** [comment]
Thanks, will do.
