### ISSUE TITLE
Swap "Brightness" and "White Value" in Lonsonho-9W-E27-RGBWW-bulb?

### ISSUE THREAD

**Issue by thi-baut** [jonathanadams/esphome-configs#75]
Hi and first thanks for proposing this! 

The Lonsonho-9W-E27-RGBWW-bulb.md (almost) works with these light bulbs: https://www.kogan.com/au/buy/kogan-smarterhome10w-rgb-cct-colour-warmcool-white-smart-bulb-e27-pack-2/ 

There is 1 glitch: in Home Assistant the "Brightness" and "Light Value" sliders need to be swapped. Sliding the brightness slider currently makes the light warmer/whiter, and sliding the light value one makes it more or less white. 

I'm not sure how to fix this, can you please advise how to edit the .yaml?

**Comment by jonathanadams** [comment]
As I don't have the particular bulbs you are referring to I won't be able to provide a solution.

In regards to editing the yaml my guess is that you would need to swap the respective GPIO for brightness and light value in the config for your new bulb.
